"""Generate committed JSON Schemas from strict Pydantic contracts."""

from __future__ import annotations

import json
from pathlib import Path

from credo_count_sde_v4.contracts import (
    ArtifactRef,
    B0ParentResolutionReceiptV1,
    BaselineInformationSet,
    BaselineRegistry,
    CandidateSelectionPlan,
    CheckpointMultinomialDecoderContract,
    ClaimRegistry,
    CompiledRunContract,
    ComponentTestContract,
    ComponentTestReceipt,
    ComponentTestReceiptV2,
    ContextAuditContract,
    CountRepresentationBundle,
    CountStoreManifest,
    DenominatorContract,
    DynamicsCheckpoint,
    EffectHierarchyContract,
    EligibilityManifest,
    EvaluationBundleManifest,
    EvaluationCheckpoint,
    EvaluationPlan,
    ExposureRegistry,
    FeatureIndex,
    FoldNativeCompactViewContractV1,
    FoldNativeCompactViewContractV2,
    FoldNativeCompactViewContractV3,
    G00CCommonSupportMetricReceiptV1,
    G00CCommonSupportPriorV2,
    G00CCompactVerificationReceiptV2,
    G00CD1ExecutionAuthorityFreezeV1,
    G00CD1ExecutionAuthorityFreezeV2,
    G00CDecisionReceipt,
    G00CDecisionReceiptV2,
    G00CDecisionReceiptV3,
    G00CDecisionReceiptV4,
    G00CExecutionBundle,
    G00CExecutionBundleV2,
    G00CExecutionBundleV3,
    G00CExecutionBundleV4,
    G00CFeatureSelectionResultV3,
    G00CMaterializationReceiptV3,
    G00CPublicationManifestV3,
    G00CRefitReplayReceiptV3,
    G00CRefitSeedScheduleV1,
    G00CSamplerEvidenceV3,
    G00CSamplerPlanV3,
    G00CSampleSizeExtensionFreezeV1,
    G00CSampleSizeSelectionResultV3,
    G00CSelectionFreezeContractV1,
    G00CSupportAuditContractV2,
    G00CSupportAuditReceiptV3,
    G00SourceAuthorityV1,
    G00SourceAuthorityV2,
    G00SourcePlaneV2Amendment,
    G00SourcePlaneV2AmendmentReceipt,
    G14MultiplicityContract,
    G14RobustnessPlan,
    G14SealContract,
    ImplementationCapabilities,
    InferenceBundleManifest,
    InputViewArtifact,
    IntegratedLoaderQualificationContractV1,
    IntegratedLoaderQualificationContractV2,
    IntegratedLoaderQualificationReceiptV1,
    IntegratedLoaderQualificationReceiptV2,
    LegacyParentAttestationReceiptV1,
    LegacyParentAttestationTestContractV1,
    LegacyParentAttestationV1,
    MultiplicityPlan,
    ParticleEngineQualificationBundle,
    ParticleEngineTestReceipt,
    PhysicalGrid,
    PhysicalPoolConditionalReactionBundle,
    PhysicalPoolConditionalReactionReceipt,
    PoolContract,
    PooledFiniteMeasureBundle,
    PooledReactionLikelihoodBundle,
    PooledReactionLikelihoodReceipt,
    PredictionQuery,
    PreparedRepresentation,
    PreregistrationRef,
    RawCountMassNoiseAmendment,
    RawCountMassNoiseAmendmentReceipt,
    RawCountMassNoiseBundle,
    RawCountMassNoiseReceipt,
    ReactionRecoveryMetricAmendment,
    ReactionRecoveryMetricAmendmentV1,
    ReactionRecoveryQualificationBundle,
    ReactionRecoveryTestReceipt,
    ReactionRecoveryTestReceiptV1,
    ReactionRecoveryTestReceiptV3,
    RepresentationCheckpoint,
    RowIndex,
    SealedRunManifest,
    SelectionManifest,
    SemanticStudySnapshot,
    ShardAppendContract,
    ShardBuildCheckpoint,
    ShardedCountStoreManifest,
    SourcePlaneDerivationReceipt,
    SplitContract,
    StateSelectionCalibration,
    StateSelectionCalibrationResults,
    TransportTopologyContract,
    VirtualCanonicalCountStoreManifestV1,
    VirtualCanonicalCountStoreManifestV2,
)

MODELS = {
    "artifact-ref.v1.json": ArtifactRef,
    "semantic-snapshot.v1.json": SemanticStudySnapshot,
    "count-store.v1.json": CountStoreManifest,
    "sharded-count-store.v1.json": ShardedCountStoreManifest,
    "virtual-canonical-count-store.v1.json": VirtualCanonicalCountStoreManifestV1,
    "virtual-canonical-count-store.v2.json": VirtualCanonicalCountStoreManifestV2,
    "g00-source-authority.v1.json": G00SourceAuthorityV1,
    "g00-source-authority.v2.json": G00SourceAuthorityV2,
    "fold-native-compact-view.v1.json": FoldNativeCompactViewContractV1,
    "fold-native-compact-view.v2.json": FoldNativeCompactViewContractV2,
    "fold-native-compact-view.v3.json": FoldNativeCompactViewContractV3,
    "g00-source-plane-v2-amendment.v1.json": G00SourcePlaneV2Amendment,
    "g00-source-plane-v2-amendment-receipt.v1.json": G00SourcePlaneV2AmendmentReceipt,
    "source-plane-derivation-receipt.v1.json": SourcePlaneDerivationReceipt,
    "legacy-parent-attestation.v1.json": LegacyParentAttestationV1,
    "legacy-parent-attestation-test-contract.v1.json": (LegacyParentAttestationTestContractV1),
    "legacy-parent-attestation-receipt.v1.json": LegacyParentAttestationReceiptV1,
    "b0-parent-resolution-receipt.v1.json": B0ParentResolutionReceiptV1,
    "g00c-execution-bundle.v1.json": G00CExecutionBundle,
    "g00c-decision-receipt.v1.json": G00CDecisionReceipt,
    "g00c-compact-verification-receipt.v2.json": G00CCompactVerificationReceiptV2,
    "g00c-execution-bundle.v2.json": G00CExecutionBundleV2,
    "g00c-decision-receipt.v2.json": G00CDecisionReceiptV2,
    "g00c-execution-bundle.v3.json": G00CExecutionBundleV3,
    "g00c-decision-receipt.v3.json": G00CDecisionReceiptV3,
    "g00c-execution-bundle.v4.json": G00CExecutionBundleV4,
    "g00c-decision-receipt.v4.json": G00CDecisionReceiptV4,
    "g00c-selection-freeze.v1.json": G00CSelectionFreezeContractV1,
    "g00c-d1-execution-authority-freeze.v1.json": G00CD1ExecutionAuthorityFreezeV1,
    "g00c-d1-execution-authority-freeze.v2.json": G00CD1ExecutionAuthorityFreezeV2,
    "g00c-sample-size-extension-freeze.v1.json": G00CSampleSizeExtensionFreezeV1,
    "g00c-common-support-prior.v2.json": G00CCommonSupportPriorV2,
    "g00c-common-support-metric-receipt.v1.json": G00CCommonSupportMetricReceiptV1,
    "g00c-support-audit-contract.v2.json": G00CSupportAuditContractV2,
    "g00c-refit-seed-schedule.v1.json": G00CRefitSeedScheduleV1,
    "g00c-sampler-plan.v3.json": G00CSamplerPlanV3,
    "g00c-sampler-evidence.v3.json": G00CSamplerEvidenceV3,
    "g00c-refit-replay-receipt.v3.json": G00CRefitReplayReceiptV3,
    "g00c-support-audit-receipt.v3.json": G00CSupportAuditReceiptV3,
    "g00c-materialization-receipt.v3.json": G00CMaterializationReceiptV3,
    "g00c-publication-manifest.v3.json": G00CPublicationManifestV3,
    "g00c-feature-selection-result.v3.json": G00CFeatureSelectionResultV3,
    "g00c-sample-size-selection-result.v3.json": G00CSampleSizeSelectionResultV3,
    "integrated-loader-qualification-contract.v1.json": (IntegratedLoaderQualificationContractV1),
    "integrated-loader-qualification-contract.v2.json": (IntegratedLoaderQualificationContractV2),
    "integrated-loader-qualification-receipt.v1.json": IntegratedLoaderQualificationReceiptV1,
    "integrated-loader-qualification-receipt.v2.json": IntegratedLoaderQualificationReceiptV2,
    "count-representation-bundle.v1.json": CountRepresentationBundle,
    "checkpoint-multinomial-decoder.v2.json": CheckpointMultinomialDecoderContract,
    "claim-registry.v2.json": ClaimRegistry,
    "g14-robustness-plan.v2.json": G14RobustnessPlan,
    "g14-multiplicity-contract.v2.json": G14MultiplicityContract,
    "g14-seal-contract.v2.json": G14SealContract,
    "row-index.v1.json": RowIndex,
    "feature-index.v1.json": FeatureIndex,
    "pooled-finite-measure-bundle.v1.json": PooledFiniteMeasureBundle,
    "pooled-reaction-likelihood-bundle.v1.json": PooledReactionLikelihoodBundle,
    "pooled-reaction-likelihood-receipt.v1.json": PooledReactionLikelihoodReceipt,
    "physical-pool-conditional-reaction-bundle.v2.json": PhysicalPoolConditionalReactionBundle,
    "physical-pool-conditional-reaction-receipt.v2.json": PhysicalPoolConditionalReactionReceipt,
    "component-test-contract.v1.json": ComponentTestContract,
    "component-test-receipt.v1.json": ComponentTestReceipt,
    "component-test-receipt.v2.json": ComponentTestReceiptV2,
    "particle-engine-qualification-bundle.v1.json": ParticleEngineQualificationBundle,
    "particle-engine-test-receipt.v1.json": ParticleEngineTestReceipt,
    "raw-count-mass-noise-bundle.v1.json": RawCountMassNoiseBundle,
    "raw-count-mass-noise-receipt.v1.json": RawCountMassNoiseReceipt,
    "raw-count-mass-noise-amendment.v1.json": RawCountMassNoiseAmendment,
    "raw-count-mass-noise-amendment-receipt.v1.json": RawCountMassNoiseAmendmentReceipt,
    "reaction-recovery-qualification-bundle.v1.json": ReactionRecoveryQualificationBundle,
    "reaction-recovery-test-receipt.v1.json": ReactionRecoveryTestReceiptV1,
    "reaction-recovery-test-receipt.v2.json": ReactionRecoveryTestReceipt,
    "reaction-recovery-test-receipt.v3.json": ReactionRecoveryTestReceiptV3,
    "reaction-recovery-metric-amendment.v1.json": ReactionRecoveryMetricAmendmentV1,
    "reaction-recovery-metric-amendment.v2.json": ReactionRecoveryMetricAmendment,
    "split-contract.v1.json": SplitContract,
    "input-view.v1.json": InputViewArtifact,
    "effect-hierarchy.v1.json": EffectHierarchyContract,
    "transport-topology.v1.json": TransportTopologyContract,
    "denominator-contract.v1.json": DenominatorContract,
    "pool-contract.v1.json": PoolContract,
    "physical-grid.v1.json": PhysicalGrid,
    "implementation-capabilities.v1.json": ImplementationCapabilities,
    "prepared-representation.v1.json": PreparedRepresentation,
    "compiled-run.v1.json": CompiledRunContract,
    "exposure-registry.v1.json": ExposureRegistry,
    "eligibility-manifest.v1.json": EligibilityManifest,
    "preregistration-ref.v1.json": PreregistrationRef,
    "multiplicity-plan.v1.json": MultiplicityPlan,
    "candidate-selection-plan.v1.json": CandidateSelectionPlan,
    "state-selection-calibration.v1.json": StateSelectionCalibration,
    "state-selection-calibration-results.v1.json": StateSelectionCalibrationResults,
    "selection-manifest.v1.json": SelectionManifest,
    "baseline-information-set.v1.json": BaselineInformationSet,
    "baseline-registry.v1.json": BaselineRegistry,
    "prediction-query.v1.json": PredictionQuery,
    "evaluation-plan.v1.json": EvaluationPlan,
    "context-audit.v1.json": ContextAuditContract,
    "shard-build-checkpoint.v1.json": ShardBuildCheckpoint,
    "shard-append-contract.v1.json": ShardAppendContract,
    "representation-checkpoint.v1.json": RepresentationCheckpoint,
    "dynamics-checkpoint.v1.json": DynamicsCheckpoint,
    "evaluation-checkpoint.v1.json": EvaluationCheckpoint,
    "inference-bundle.v1.json": InferenceBundleManifest,
    "evaluation-bundle.v1.json": EvaluationBundleManifest,
    "sealed-run.v1.json": SealedRunManifest,
}

# Immutable accepted schemas whose active construction advanced to v2. They are
# validated by explicit v1 models and compatibility tests, never regenerated.
LEGACY_SCHEMAS = {
    "checkpoint-multinomial-decoder.v1.json",
    "claim-registry.v1.json",
    "g14-multiplicity-contract.v1.json",
    "g14-robustness-plan.v1.json",
    "g14-seal-contract.v1.json",
}


def main() -> None:
    root = Path(__file__).resolve().parents[1] / "schemas"
    root.mkdir(exist_ok=True)
    for name, model in MODELS.items():
        payload = model.model_json_schema()
        payload["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        payload["$id"] = f"https://credo.local/schemas/{name}"
        (root / name).write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
